name: Performance

on:
  pull_request:
  push:
    branches: [main]

jobs:
  detectChangedSourceFiles:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changed-files-yaml.outputs.src_any_changed }}
    steps:
      - uses: actions/checkout@v3
      - name: Detect changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            src:
              - packages/formik/src/**
              - packages/formik/package.json
              - packages/formik-native/src/**
              - packages/formik-native/package.json
  benchmark:
    if: needs.detectChangedSourceFiles.outputs.changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Benchmark
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Detect changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            src:
              - packages/formik/src/**
              - packages/formik-native/src/**

      - name: Install & build
        run: |
          node --version
          npm --version
          yarn --version
          yarn install --frozen-lockfile
          yarn build:benchmark

      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./benchmark-cache
          key: ${{ runner.os }}-benchmark

      - name: Run benchmark
        run: yarn benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: benchmarkjs
          external-data-json-path: ./benchmark-cache/benchmark-data.json
          output-file-path: output.txt
          # comment for PRs that's updated with current perf relative to baseline (main)
          summary-always: true
          # warn if slowness is detected; might be transient on rerun
          alert-threshold: 110%
          comment-on-alert: true
          fail-on-alert: true
          # if things get considerably slower, deny the PR
          fail-threshold: 120%
          # needed for commenting on PRs
          github-token: ${{ secrets.GITHUB_TOKEN }}
