name: Performance

on:
  pull_request:
  push:
    branches: [main]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ['18.x']

    name: Test on node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node }}

      - name: Detect changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            src:
              - packages/formik/src/**
              - packages/formik-native/src/**

      - name: Install & build
        if: steps.changed-files-yaml.outputs.src_any_changed == 'true'
        run: |
          node --version
          npm --version
          yarn --version
          yarn install --frozen-lockfile
          yarn build:benchmark

      - name: Download previous benchmark data
        if: steps.changed-files-yaml.outputs.src_any_changed == 'true'
        uses: actions/cache@v3
        with:
          path: ./benchmark-cache
          key: ${{ runner.os }}-benchmark

      - name: Run benchmark
        if: steps.changed-files-yaml.outputs.src_any_changed == 'true'
        run: yarn benchmark

      - name: Store benchmark result
        if: steps.changed-files-yaml.outputs.src_any_changed == 'true'
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: benchmarkjs
          external-data-json-path: ./benchmark-cache/benchmark-data.json
          output-file-path: output.txt
          # comment for PRs that's updated with current perf relative to baseline (main)
          summary-always: true
          # warn if slowness is detected; might be transient on rerun
          alert-threshold: 110%
          comment-on-alert: true
          fail-on-alert: true
          # if things get considerably slower, deny the PR
          fail-threshold: 120%
          # needed for commenting on PRs
          github-token: ${{ secrets.GITHUB_TOKEN }}
