name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Netlify to trigger rebuild
        run: curl -X POST -d {} ${{ secrets.NETLIFY_URL }}
