name: Compressed Size

on: [pull_request]

jobs:
  detectChangedSourceFiles:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changed-files-yaml.outputs.src_any_changed }}
    steps:
      - uses: actions/checkout@v3
      - name: Detect changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            src:
              - packages/formik/src/**
              - packages/formik-native/src/**
  build:
    if: needs.detectChangedSourceFiles.outputs.changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          build-script: 'turbo run build --filter {./packages/*}...'
